import { Account, Budget, FinancialGoal, Transaction, User } from '@/types';

export const INITIAL_USER: User = {
  id: 'usr_101',
  name: 'Alex Morgan',
  email: 'alex.morgan@fintrack.app',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  currency: 'USD',
  monthlyBudgetLimit: 6500,
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_1',
    name: 'Primary Checking',
    type: 'checking',
    balance: 12450.80,
    accountNumber: '•••• 4821',
    institution: 'Chase Bank',
    color: '#6366f1',
    currency: 'USD',
    updatedAt: '2026-09-29T14:30:00Z',
  },
  {
    id: 'acc_2',
    name: 'High-Yield Savings',
    type: 'savings',
    balance: 45890.50,
    accountNumber: '•••• 8912',
    institution: 'Marcus Goldman Sachs',
    color: '#10b981',
    currency: 'USD',
    updatedAt: '2026-09-30T08:15:00Z',
  },
  {
    id: 'acc_3',
    name: 'Sapphire Reserve Credit',
    type: 'credit',
    balance: -2150.40,
    accountNumber: '•••• 3094',
    institution: 'Chase Bank',
    color: '#f43f5e',
    currency: 'USD',
    updatedAt: '2026-09-30T01:00:00Z',
  },
  {
    id: 'acc_4',
    name: 'Vanguard Index Portfolio',
    type: 'investment',
    balance: 78400.00,
    accountNumber: '•••• 7710',
    institution: 'Vanguard',
    color: '#06b6d4',
    currency: 'USD',
    updatedAt: '2026-09-28T16:00:00Z',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bdg_1',
    category: 'Housing',
    targetAmount: 2200,
    spentAmount: 2200,
    period: 'monthly',
    color: '#6366f1',
    iconName: 'Home',
  },
  {
    id: 'bdg_2',
    category: 'Food & Dining',
    targetAmount: 900,
    spentAmount: 645.20,
    period: 'monthly',
    color: '#f59e0b',
    iconName: 'Utensils',
  },
  {
    id: 'bdg_3',
    category: 'Shopping',
    targetAmount: 600,
    spentAmount: 520.00,
    period: 'monthly',
    color: '#a855f7',
    iconName: 'ShoppingBag',
  },
  {
    id: 'bdg_4',
    category: 'Transportation',
    targetAmount: 450,
    spentAmount: 310.80,
    period: 'monthly',
    color: '#06b6d4',
    iconName: 'Car',
  },
  {
    id: 'bdg_5',
    category: 'Entertainment',
    targetAmount: 350,
    spentAmount: 280.50,
    period: 'monthly',
    color: '#ec4899',
    iconName: 'Film',
  },
  {
    id: 'bdg_6',
    category: 'Utilities',
    targetAmount: 300,
    spentAmount: 240.00,
    period: 'monthly',
    color: '#64748b',
    iconName: 'Zap',
  },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 'gl_1',
    name: 'Emergency Reserve (6 Months)',
    targetAmount: 30000,
    currentAmount: 24500,
    deadline: '2026-12-31',
    category: 'Savings',
    color: '#10b981',
    iconName: 'ShieldCheck',
    notes: 'Goal to cover 6 months of living expenses in HYSA.',
  },
  {
    id: 'gl_2',
    name: 'Japan Autumn Trip',
    targetAmount: 6500,
    currentAmount: 4800,
    deadline: '2026-10-15',
    category: 'Travel',
    color: '#14b8a6',
    iconName: 'Plane',
    notes: 'Flight, Ryokan stays, and culinary tour.',
  },
  {
    id: 'gl_3',
    name: 'Tesla Model Y Down Payment',
    targetAmount: 15000,
    currentAmount: 8900,
    deadline: '2027-03-30',
    category: 'Vehicle',
    color: '#06b6d4',
    iconName: 'Car',
    notes: 'Targeting 20% down payment.',
  },
  {
    id: 'gl_4',
    name: 'Tech Stack & Setup Refresh',
    targetAmount: 3500,
    currentAmount: 3500,
    deadline: '2026-08-30',
    category: 'Gadgets',
    color: '#6366f1',
    iconName: 'Laptop',
    notes: 'Completed M3 Max MacBook & Dual 4K monitors!',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    title: 'Senior Software Tech Corp Salary',
    amount: 8500.00,
    type: 'income',
    category: 'Salary',
    date: '2026-09-28',
    accountId: 'acc_1',
    accountName: 'Primary Checking',
    status: 'completed',
    merchant: 'Acme Corp',
    notes: 'Bi-weekly payroll direct deposit',
  },
  {
    id: 'tx_2',
    title: 'Luxury Apartment Rent',
    amount: 2200.00,
    type: 'expense',
    category: 'Housing',
    date: '2026-09-27',
    accountId: 'acc_1',
    accountName: 'Primary Checking',
    status: 'completed',
    merchant: 'Skyline Residences',
  },
  {
    id: 'tx_3',
    title: 'Whole Foods Market',
    amount: 184.60,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-09-26',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Whole Foods',
  },
  {
    id: 'tx_4',
    title: 'Uber Eats - Sushi Dinner',
    amount: 68.40,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-09-25',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Uber Eats',
  },
  {
    id: 'tx_5',
    title: 'Freelance UI/UX Design Client',
    amount: 1750.00,
    type: 'income',
    category: 'Freelance',
    date: '2026-09-24',
    accountId: 'acc_1',
    accountName: 'Primary Checking',
    status: 'completed',
    merchant: 'Stripe Payout',
  },
  {
    id: 'tx_6',
    title: 'Apple Store - AirPods Max',
    amount: 549.00,
    type: 'expense',
    category: 'Shopping',
    date: '2026-09-22',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Apple Fifth Ave',
  },
  {
    id: 'tx_7',
    title: 'Tesla Supercharger',
    amount: 28.50,
    type: 'expense',
    category: 'Transportation',
    date: '2026-09-21',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Tesla Motors',
  },
  {
    id: 'tx_8',
    title: 'Netflix & Spotify Subscriptions',
    amount: 32.98,
    type: 'expense',
    category: 'Subscriptions',
    date: '2026-09-20',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Digital Media',
  },
  {
    id: 'tx_9',
    title: 'Concert Tickets - Summer Fest',
    amount: 220.00,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-09-18',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Ticketmaster',
  },
  {
    id: 'tx_10',
    title: 'Consolidated Edison Power & Gas',
    amount: 145.20,
    type: 'expense',
    category: 'Utilities',
    date: '2026-09-15',
    accountId: 'acc_1',
    accountName: 'Primary Checking',
    status: 'completed',
    merchant: 'ConEd',
  },
  {
    id: 'tx_11',
    title: 'S&P 500 Index Monthly Contribution',
    amount: 1500.00,
    type: 'transfer',
    category: 'Investments',
    date: '2026-09-14',
    accountId: 'acc_4',
    accountName: 'Vanguard Index Portfolio',
    status: 'completed',
    merchant: 'Vanguard Auto-Invest',
  },
  {
    id: 'tx_12',
    title: 'Equinox Gym Membership',
    amount: 280.00,
    type: 'expense',
    category: 'Healthcare',
    date: '2026-09-10',
    accountId: 'acc_3',
    accountName: 'Sapphire Reserve Credit',
    status: 'completed',
    merchant: 'Equinox Club',
  }
];

export const MONTHLY_INCOME_VS_EXPENSE = [
  { month: 'Apr', income: 9800, expense: 4200 },
  { month: 'May', income: 10200, expense: 4800 },
  { month: 'Jun', income: 9900, expense: 4100 },
  { month: 'Jul', income: 10500, expense: 5200 },
  { month: 'Aug', income: 10800, expense: 4600 },
  { month: 'Sep', income: 10250, expense: 4196 },
];

export const NET_WORTH_HISTORY = [
  { month: 'Apr', netWorth: 121000, assets: 125000, liabilities: 4000 },
  { month: 'May', netWorth: 124500, assets: 128000, liabilities: 3500 },
  { month: 'Jun', netWorth: 128200, assets: 131500, liabilities: 3300 },
  { month: 'Jul', netWorth: 131000, assets: 134000, liabilities: 3000 },
  { month: 'Aug', netWorth: 132400, assets: 135000, liabilities: 2600 },
  { month: 'Sep', netWorth: 134590, assets: 136740, liabilities: 2150 },
];
